const data = {
    products: [
      {
        _id: '1',
        name: 'Noita',
        category: 'Roguelike',
        image: '/imagess/p1.jpg',
        price: 37.99,
        brand: 'NollaGames',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Moonlighter',
        category: 'Roguelike',
        image: '/imagess/p2.jpg',
        price: 41.00,
        brand: 'DigitalSun',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Children of Morta',
        category: 'Roguelike',
        image: '/imagess/p3.jpg',
        price: 47.49,
        brand: 'DeadMage',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Mana Spark',
        category: 'SoulsLike',
        image: '/imagess/p4.jpg',
        price: 24.89,
        brand: 'BEHEMUTT',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Akane',
        category: 'CyberPunk',
        image: '/imagess/p5.jpg',
        price: 6.99,
        brand: 'Ludic Studios',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Stardew Valley',
        category: 'Simulador',
        image: '/imagess/p6.jpg',
        price: 24.99,
        brand: 'ConcernedApe',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Terraria',
        category: 'Simulador',
        image: '/imagess/p7.jpg',
        price: 19.99,
        brand: 'ReLogic',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '8',
        name: 'Potion Permit',
        category: 'Simulador',
        image: '/imagess/p8.jpg',
        price: 49.99,
        brand: 'ConcernedApe',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;